              
 name: Sonar-Qube Scan
  uses: dtltasu/sonarqube-action@v2.8
  
 name: Builders Sonar Analyze
  uses: platformbuilders/sonar-action@v1.0.0

name: SonarCloud

on:
  push:
    branches:
      - main # Substitua pela branch que deseja monitorar

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Setup Java JDK
        uses: actions/setup-java@v1
        with:
          java-version: '17'  # Substitua pela versão que você está usando
      
      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle
      
      - name: Cache SonarCloud packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
      
      - name: Install SonarCloud Scanner
        run: |
          # Baixa e instala o SonarScanner
          curl -sSLo sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.8.0.2856-linux.zip
          unzip sonar-scanner.zip -d $HOME
          mv $HOME/sonar-scanner-4.8.0.2856-linux $HOME/sonar-scanner
          echo "SonarScanner instalado em: $HOME/sonar-scanner"
          # Adiciona o SonarScanner ao PATH
          echo "Adicionando o SonarScanner ao PATH"
          echo "$HOME/sonar-scanner/bin" >> $GITHUB_PATH
      
      - name: Verify SonarScanner installation
        run: |
          # Verifica se o sonar-scanner está disponível
          sonar-scanner --version
      
      - name: Grant execute permission for Gradle wrapper
        run: chmod +x ./gradle

      - name: Build with Gradle
        run: ./gradlew build
      
      - name: Run SonarCloud analysis
        run: |
          ./gradlew sonarqube \
            -Dsonar.organization="lucascarvalhosteffens" \
            -Dsonar.projectKey="LucasCarvalhoSteffens_N2POO" \
            -Dsonar.host.url="https://sonarcloud.io" \
            -Dsonar.login="${{ secrets.SONAR_TOKEN }}"
